---
all:
  hosts:
    nexus-01:
      ansible_host: 89.169.155.132
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: centos
    ansible_ssh_private_key_file: /home/vgorshkov/.ssh/netology-ext-key
